"""create user activity logs

Revision ID: 9a791178f426
Revises: 7f26e4e8178a
Create Date: 2026-08-30 19:35:27.282842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a791178f426'
down_revision: Union[str, Sequence[str], None] = '7f26e4e8178a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('activity_metadata', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activities_action'), 'user_activities', ['action'], unique=False)
    op.create_index(op.f('ix_user_activities_occurred_at'), 'user_activities', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_user_activities_resource_id'), 'user_activities', ['resource_id'], unique=False)
    op.create_index(op.f('ix_user_activities_resource_type'), 'user_activities', ['resource_type'], unique=False)
    op.create_index(op.f('ix_user_activities_user_id'), 'user_activities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_activities_user_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_resource_type'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_resource_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_occurred_at'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_action'), table_name='user_activities')
    op.drop_table('user_activities')
    # ### end Alembic commands ###
